version: 2

jobs:

  build-python36:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update ; apt-get install -y make git
      - checkout
      - run: make deps-ubuntu deps-test deps install repo/assets
      - run: make test
      - run: make test-cli
workflows:
  version: 2
  build:
    jobs:
      - build-python36
