version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:

  build-python36:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y --no-install-recommends software-properties-common
      - run: add-apt-repository -y ppa:alex-p/tesseract-ocr
      - run: apt-get install -y --no-install-recommends make git curl
      - checkout
      - run: make deps-ubuntu deps-test deps install repo/assets
      - run: make test-cli
      - run: make coverage
      - codecov/upload

workflows:
  build:
    jobs:
      - build-python36
